### PR TITLE
iter: support more types for N()

### PR DESCRIPTION
**Pull request by voutasaurus**
@bmizerany did this today:
```
func n(b *testing.T) []struct{} {
        return make([]struct{}, b.N)
}

func BenchmarkNewParent(b *testing.B) {
        b.ReportAllocs()
        for range n(b) {
                
        }
}
```

I immediately thought of iter and felt compelled to write this.

Please enjoy my proposal for what iter could be.

### CODE REVIEW

**Comment by bradfitz** [comment]
Yeah, no. Sorry. Feel free to fork.

**Comment by bmizerany** [comment]
I was just having fun, @voutasaurus. ;)

**Comment by voutasaurus** [comment]
In case it wasn't clear this PR was intended as a joke

**Comment by bradfitz** [comment]
I figured. :)

But this repo is a joke too, and the joke is funniest if the git history has exactly one commit. :)

**Comment by voutasaurus** [comment]
Agreed. I think mine is funnier in its own repo too. I wouldn't want to squash the panic fix. :)

**Pull request closed without merging**
